#!/usr/bin/env bash
# a Bash script that displays listening ports:
#+ That only shows listening sockets
#+ That shows the PID and name of the program to which each socket belongs


# Display listening ports with PID and program name

# Display TCP ports
echo "TCP ports:"
sudo ss -tlnp | grep 'LISTEN'

# Display UDP ports
echo "UDP ports:"
sudo ss -ulnp | grep 'UNCONN'

